import{i,S as u}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();function f(s){const o="https://pixabay.com/api/",t=new URLSearchParams({key:"43014445-2d3e2fe82a6f953d204684055",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});g();const n=`${o}?${t}`;return fetch(n).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function d(s){if(s.length===0)i.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const o=s.map(t=>`<li class="photos-list-item">
  <a class="photos-list-link" href="${t.largeImageURL}">
  <img class="photo" src="${t.webformatURL}" alt="${t.tags}"/>
  </a>
  <ul class="photo-information-container">
  <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t.likes}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${t.views}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${t.comments}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${t.downloads}</p></li>
  </ul>
  </li>`).join("");m.insertAdjacentHTML("beforeend",o),h.refresh()}}const h=new u(".gallery a",{captionDelay:250,captionsData:"alt"}),l=document.querySelector(".loader");l.style.display="none";const g=()=>{l.style.display="flex"},p=()=>{l.style.display="none"},m=document.querySelector(".gallery"),c=document.querySelector(".form");c.elements.query;c.addEventListener("submit",y);function y(s){s.preventDefault();const o=s.target.elements.query.value.trim();o!==""?(m.innerHTML="",f(o).then(t=>{d(t.hits),c.reset(),p()}).catch(t=>{console.log(t),p(),i.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})})):i.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
